export enum StatusLocacao {
    DISPONIVEL = 'DISPONIVEL',
    INDISPONIVEL = 'INDISPONIVEL',
    ALUGADO = 'ALUGADO',
    FINALIZADA = 'FINALIZADA',
    CANCELADA = 'CANCELADA',
    EM_ANDAMENTO = 'EM_ANDAMENTO',
  }
  